### ISSUE TITLE
Shelf: StoreLabware - add checking for duplicate barcode

### ISSUE THREAD

**Issue by dhanarfmlx** [wandayusufalvian/c_sharp#10]
https://github.com/wandayusufalvian/c_sharp/blob/4d5a51f02b5e22c30fc866c0f14da21949bd9520/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L87

Throw exception if duplicate barcode found

**Comment by wandayusufalvian** [comment]
done

**Comment by dhanarfmlx** [comment]
https://github.com/wandayusufalvian/c_sharp/blob/3f86594dbebabb5822ea863d32a3e1ae2fa88549/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L95

https://github.com/wandayusufalvian/c_sharp/blob/3f86594dbebabb5822ea863d32a3e1ae2fa88549/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L112

Do not check for string null or empty. Use LINQ Any instead: https://www.codingame.com/playgrounds/213/using-c-linq---a-practical-overview/any-and-all

**Comment by wandayusufalvian** [comment]
done
