### ISSUE TITLE
LabwareStorageService: GetEmptyShelfId, GetEmptyShelfName

### ISSUE THREAD

**Issue by dhanarfmlx** [wandayusufalvian/c_sharp#12]
https://github.com/wandayusufalvian/c_sharp/blob/3f86594dbebabb5822ea863d32a3e1ae2fa88549/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L16

https://github.com/wandayusufalvian/c_sharp/blob/3f86594dbebabb5822ea863d32a3e1ae2fa88549/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L42

Do not use ToList(). Just drop the reverse logic. Performance reasons.

Tell me if you have any questions.

**Comment by wandayusufalvian** [comment]
Done
