### ISSUE TITLE
LabwareStorageService: StoreLabware - add check invalid shelf id/name

### ISSUE THREAD

**Issue by dhanarfmlx** [wandayusufalvian/c_sharp#13]
https://github.com/wandayusufalvian/c_sharp/blob/1e530ef9d30540715d3fca44691e692c834ef730/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L101

https://github.com/wandayusufalvian/c_sharp/blob/1e530ef9d30540715d3fca44691e692c834ef730/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L122

Assumption is correct, but we need to add checking if shelf id/name is invalid. If invalid, throw argument exception with message invalid name/id

**Comment by wandayusufalvian** [comment]
done
