### ISSUE TITLE
LabwareStorageService: Turns out we are not allowed to store plates in trough shelf

### ISSUE THREAD

**Issue by dhanarfmlx** [wandayusufalvian/c_sharp#15]
https://github.com/wandayusufalvian/c_sharp/blob/1e530ef9d30540715d3fca44691e692c834ef730/shelf/CellCulture.Common.Database.LabwareStorage/LabwareStorageService.cs#L23

Remove this. Turns out that we are not allowed to store plates in troughs. This is due to limited trough space.

**Comment by wandayusufalvian** [comment]
done
